### ISSUE TITLE
Breaking change when upgrading from 3.7 to 3.10

### ISSUE THREAD

**Issue by JamesFaix** [nunit/nunit#2793]
My project uses many attributes inheriting from `PropertyAttribute`, and some classes for checking the properties assigned to a test via these attributes, using the `PropertyAttribute.Properties` property.  In 3.7 this property was of type `IPropertyBag`, but in 3.10 this is of type `PropertyBagAdapter`, which looks like a Decorator of `IPropertyBag`, but does not implement the `IPropertyBag` interface.  I have created several extension methods for `IPropertyBag` to make it easier to use, but now the nUnit API does not directly expose instances of `IPropertyBag`, which means I need to rewrite a lot of my property-related code.  

I can work around the problem by changing my extension methods to work on `Dictionary<string, List<object>>`, and creating a method to convert `PropertyBagAdapter` to `Dictionary<string, List<object>>`.  But this was a surprising change for a minor version, and the exposed API of `PropertyBagAdapter` does not seem very complete. (Why not implement `IEnumerable` or other collection methods which would likely be desired?)

**Comment by CharliePoole** [comment]
Someone wrote that if you expose any code - even erroneous code - to a large number of users, some of them will make use of it and you will have to maintain it forever. 😄 We were trying to avoid that.

If you take a look at the earlier. code in `TestContext`, you will see that we don't directly expose the key internal classes `Test` and `TestResult` to the user. Instead we provide adapters to give the user read access to key fields of each of them. But the `Properties` field of `CurrentTest`, instead of using an adapter, gave you access directly into the properties of the `Test` class. That meant a user could change properties, including those internal properties that NUnit itself depends on.

So, removing write access to the properties was a deliberate bug fix. Anyone who had come to depend on that was, unfortunately, out of luck, because the ability to change properties is too dangerous for a user-level API.

We can still change the interface (adding to it) if we avoid adding or changing properties. What do you suggest?

**Comment by rprouse** [comment]
I've marked this as an enhancement to add a **read-only** collection interface to `PropertyBagAdapter` to make it easier to use. I've also added the design label until we figure out what that interface should be. You have a decent use-case for better access to the properties and we should support that.

**Comment by CharliePoole** [comment]
@rprouse That makes sense. As an originally internal interface, `IPropertyBag` assumes that the caller knows which properties are multi-valued and which are not. Barring a more encapsulated re-design of properties themselves, users needs something more general.

Whoever designs the interface may want to consider #2674 as well.

**Comment by JamesFaix** [comment]
Thanks for the quick response.  #2674 looks very relevant to my use case actually.  A lot of what I need to do with `IPropertyBag` is compare the properties during `OneTimeSetup` and `Setup` to determine what all "inherited" properties a test should have, and which method-level properties should override the values from fixture-level properties.

**Comment by qidydl** [comment]
We've been making use of TestContext.CurrentContext.Test.Properties as a way to store custom information we want available to tests. Now that this is effectively read-only, is there a suggested replacement, or are we encouraged to roll our own mechanism instead?

**Comment by rprouse** [comment]
@qidydl I would recommend implementing your own container to pass data between tests.
