### ISSUE TITLE
Is.EqualTo stopped working after upgrade from 4.0.1 to 4.1.0

### ISSUE THREAD

**Issue by Lorthiz** [nunit/nunit#4716]
I have a pretty simple use case. I have object stored in 2 formats. Original one called 'xxx' and in 'json'. 
The purpose of whole test is to verify that when 'xxx' is loaded it has the same values as pre-generated json.

The test was working before the update, now it fails. I was able to reproduce it with a simpler example:

```
using Newtonsoft.Json;
using NUnit.Framework;

   public class IsEqualTestAfterUpgrade {

    private class TestingClass {
        public int Val { get; set; }

    }

    private const string TestingClassJson = "{val: 123}";

    [Test]
    public void Test() {
        var obj1 = JsonConvert.DeserializeObject<TestingClass>(TestingClassJson);
        var obj2 = JsonConvert.DeserializeObject<TestingClass>(TestingClassJson);

        Assert.That(obj1.Val, Is.EqualTo(123));
        Assert.That(obj1.Val, Is.EqualTo(obj2.Val));
        Assert.That(JsonConvert.SerializeObject(obj1), Is.EqualTo(JsonConvert.SerializeObject(obj2)));
        
        
        Assert.That(obj1, Is.EqualTo(obj2)); //This returns false? Why?
    }

}
```

After upgrading to 4.1.0 the `Is.EqualTo` returns false for those object, but serializing both to JSON again and comparing that passes. The thing that I can't understand is what changed and this is the only problem that popped up to my whole test suite.

**Comment by manfred-brands** [comment]
Your `TestingClass` does not implement `IEquality` so `obj1.Equals(obj2)` will always return `false`.

In 4.0, the NUnit Properties comparer was enabled by default. This caused `IsEqualTo` to compare the `Val` property and pass your test.

Because others didn't like this new behaviour, the properties comparer now needs to explicitly enabled by adding the `.UsingPropertiesComparer()` modifier. 

See the [comparing classes section in the Equal constraint](https://docs.nunit.org/articles/nunit/writing-tests/constraints/EqualConstraint.html#comparing-classesstructures) documentation.

**Comment by Lorthiz** [comment]
> Your `TestingClass` does not implement `IEquality` so `obj1.Equals(obj2)` will always return `false`.
> 
> In 4.0, the NUnit Properties comparer was enabled by default. This caused `IsEqualTo` to compare the `Val` property and pass your test.
> 
> Because others didn't like this new behaviour, the properties comparer now needs to explicitly enabled by adding the `.UsingPropertiesComparer()` modifier.
> 
> See the [comparing classes section in the Equal constraint](https://docs.nunit.org/articles/nunit/writing-tests/constraints/EqualConstraint.html#comparing-classesstructures) documentation.

Thank you very much for response! This issue caught me offguard, I opened the release notes did a quick find for `EqualTo` it did not find anything, saw that breaking changes are `none`  and I stopped reading. I should have checked it better, before posting. Sorry. Thank you very much for explanation.

**Comment by Lorthiz** [comment]
Closing issue
