### ISSUE TITLE
Multiple unannounced breaking changes in minor version

### ISSUE THREAD

**Issue by verdie-g** [nunit/nunit#4917]
Hi, we've recently finished a months old migration from 3.14 to 4.1, migrating 110K tests using `NUnit.Analyzers`. Today, I tried upgrading our version from 4.1 to 4.3.2 but to my distress I faced an important amount of compilation errors.

It seems like the new minor versions introduced several breaking changes that were not announced in the [changelog](https://docs.nunit.org/articles/nunit/release-notes/framework.html#nunit-42---august-22-2024). Here are a few simplified occurrences that I caught:
```csharp
// Example 1
Dictionary<long, float>? x = null;
Assert.That(x, Is.EqualTo(null).AsCollection);

// Example 2
Assert.That(0.0, Is.EqualTo(0L).Within(0.1));

// Example 3
Assert.That(true, Is.EqualTo(default));
```

This code builds with 4.1.0 but not 4.3.2 :(

They can all be fixed like the following but that will be weeks of extra work that I'm not sure we can afford.
```diff
// Example 1
Dictionary<long, float>? x = null;
- Assert.That(x, Is.EqualTo(null).AsCollection);
+ Assert.That(x, Is.Null);

// Example 2
- Assert.That(0.0, Is.EqualTo(0L).Within(0.1));
+ Assert.That(0.0, Is.EqualTo((double)0L).Within(0.1));

// Example 3
- Assert.That(true, Is.EqualTo(default));
+ Assert.That(true, Is.False);
```

**Comment by OsirisTerje** [comment]
@manfred-brands  Is some of this also related to #4916 ?

@verdie-g We did announce possibility of breaking code in 4.3, see https://docs.nunit.org/articles/nunit/release-notes/framework.html#nunit-430----dec-15-2024

> Be aware that this might cause compile errors in cases where the code was previously ignored

In your case though, it seems it is a bit too harsh, as numeric types that are easily comparable should work.  We will look into this too.  
Suggest you stay on 4.1 until we have an answer/fix to this, 

Thank you for the reporting!

**Comment by manfred-brands** [comment]
@verdie-g The new version is stricter than the old and tries to detect more issues at compile time.
We did debate using a major number, but decided against it as we added new overloads not changed existing ones or removed any. We did anticipate some people getting compile errors when using now illegal combinations, such as using `Within` on a `string` comparison or using `IgnoreCase` on a `double` comparison.

Unfortunately you have compile errors we didn't anticipate nor have seen in our extensive tests.
I could say that they are the result of non-ideal code, but I don't want to use that as an excuse.
Maybe the NUnit.Analyzer can be updated to detect the situations you have and offer a fix before you upgrade.

```
// Example 1
Dictionary<long, float>? x = null;
Assert.That(x, Is.EqualTo(null).AsCollection);
```

You don't specify a type and the compiler favours any overload over the `object?` one.
You need to specify the type, like in: `Is.EqualTo((Dictionary<long, float>?)null).AsCollection`
or as you said yourselves, `Is.Null` is a much better constraint.

```
// Example 2
Assert.That(0.0, Is.EqualTo(0L).Within(0.1));
```

You are comparing a value with a long (0L) and then expected it to be within 0.1.
The resolution of a long should be a long.
So you can either say: `Is.EqualTo(0L).Within(1L)` or you can use doubles as intended: `Is.EqualTo(0.0).Within(0.1)`.
You explicitly using 0L indicate that you want a long comparison not a double one.

```
// Example 3
Assert.That(true, Is.EqualTo(default));
```

The `default` keyword is dangerous as the value depends on the parameter type declared in the method called.
Previously `Is.EqualTo(object?)` means that you compared `true` with `null`.
Even though this compiles under NUnit 4.1, it doesn't do what you intended as regardless of the boolean value it always fails:
```
Assert.That(true, Is.EqualTo(default))
  Expected: null
  But was:  True
Assert.That(false, Is.EqualTo(default))
  Expected: null
  But was:  False
```

You can either use your workaround `Is.False` or if you want you can use the `Is.Default` constraint.

**Comment by OsirisTerje** [comment]
I believe it would be useful to add resolutions to these in the analyzer.

**Comment by manfred-brands** [comment]
> I believe it would be useful to add resolutions to these in the analyzer.

I thought you would say that:

* https://github.com/nunit/nunit.analyzers/issues/826
* https://github.com/nunit/nunit.analyzers/issues/827
* https://github.com/nunit/nunit.analyzers/issues/828

**Comment by verdie-g** [comment]
It looks like all breaking changes were caught at compile time and they only impacted ~50 of the 100K tests so I was able to fix them all quite easily.

**Comment by verdie-g** [comment]
I got several failing tests like this one after the upgrade
```
Assert.That(x, Is.EqualTo(0.05).Within(0.0000001))
    Expected: 0.050000000000000003d
    But was:  0.0500000007f
```
I'm not able to extract the values to build a minimal repro.

Any idea why it would break now?

**Comment by manfred-brands** [comment]
What also works is:
```csharp
object x = 0.0500000007f;
Assert.That(x, Is.EqualTo(0.05f).Within(0.0000001));
```

The problem is comparing
The failing versions calls the overload: `Assert.That<object>(x, EqualNumericConstraint<double>())`

The code checks if the actual type is the same as the expected type which fails: `float != double`.
I then tries to check if the actual type _declaration_ is a numeric type, which fails because it is `object`.
It then falls back to he pre 4.3 EqualConstraint, but forgets to add back in the tolerance.

I changed the 2nd test to check the actual type _value_ instead of the _declaration_.
Also for completeness, if that still fails, I pass the tolerance to the pre 4.3 EqualConstraint.

Finally, I raised https://github.com/nunit/nunit.analyzers/issues/837 in the nunit.analyzer project.
