### ISSUE TITLE
Is.EqualTo(double).Using(EqualityComparer<double>) causes overload ambiguity error

### ISSUE THREAD

**Issue by appel1** [nunit/nunit#4916]
Updated from NUnit 4.2.2 to 4.3.2 and now some tests fail to compile. 

We have tests like this where actual and expected are doubles and `DoubleComparer.Approximately()` is a method that returns a `EqualityComparer<double>`. 

```csharp
Assert.That(actual, Is.EqualTo(expected).Using<double>(DoubleComparer.Approximately(precision)));
```

This triggers this compilation error: 
```
error CS0121: The call is ambiguous between the following methods or properties: 'IEqualWithUsingConstraintExtensions.Using<T
Expected>(IEqualWithUsingConstraint<TExpected>, IEqualityComparer<TExpected>)' and 'IEqualWithUsingConstraintExtensions.Using<TExpected>(IEqualWithUsingConstraint<TExpected>, IEqualityComparer)'
```

Current workaround is to introduce an explicit cast in our tests:
```csharp
Assert.That(actual, Is.EqualTo(expected).Using((IEqualityComparer<double>)DoubleComparer.Approximately(precision)));
```

**Comment by OsirisTerje** [comment]
@manfred-brands Comment ?

**Comment by jnm2** [comment]
For comparison, the approach Shouldly took in a very similar scenario was to only declare the new overloads for people who were targeting .NET 9, and thus using C# 13, since C# 13 respects [OverloadResolutionPriorityAttribute]: #984

**Comment by manfred-brands** [comment]
@appel1 If your `DoubleComparer.Approximately` can return the interface `IEqualityComparer<double>` there is no ambiguity and you can even drop the `<double>` part. 

There was ambiguity in 3.14 and 4.2.2 which you resolved by adding the `<double>` generic parameter, thereby excluding the non-generic `IEqualityComparer` overload.

The difference between 4.2 and 4.3 is that all `Using` overload are generic to match the type passed to `EqualTo` so that the trick to add the `<double>` to select the generic overload doesn't work.

@OsirisTerje One option would be to drop the old  `IEqualityComparer` overload for strictly typed constraints as the whole idea was to keep the generic type not to fallback to `object` for comparing. But this is likely to also break (older) code.

@jnm2 The SDK is independent of the TargetFramework. For one of my work's major projects we move up the SDK to the latest to get language features, but still need to target .NET Framework 4.8 because of 3rd party libraries that are not available for .NET Core. 

So we could put `[OverloadResolutionPriorityAttribute]` in and people only have to update the SDK to take advantage of it.
I'll try this, but the success rate for the last issue (picking `object` overload over `string`) didn't work. It always picked one or the other.

**Comment by manfred-brands** [comment]
@jnm2 If I add `[OverloadResolutionPriorityAttribute(1)]` to the overload expecting the generic `IEqualityComparer<T>`, it correctly picks the generic overload if the passed parameter implements both.
However, for parameters that only implement  `IEqualityComparer`, even if declared that way, it still wants to pick the generic overload and complains that it cannot convert the type to a `IEqualityComparer<int>` type. It looks like it now never considers the non-generic overload as a candidate.

![{A5C4282E-3890-40F3-A89E-4C100CD0D258}](https://github.com/user-attachments/assets/adc01de9-8625-45f6-8adb-686bd30981d0)

It also complains about the other `Using` overloads with `Func`.

![{154F55E5-BAB0-4D19-9E0D-626B06C1C864}](https://github.com/user-attachments/assets/07a26400-025b-4612-87c6-46a9855ba33d)

I must be missing something with this overload resolution or the implementation is not quite right.
Even though the compiler complains, Inside VS when going to definition goes to the right place.
I'm using 9.0.101 SDK.

I have pushed to code to the `Issue4916_OverloadResolutionPriority` branch, if you want to have a look.

**Comment by jnm2** [comment]
> The SDK is independent of the TargetFramework. For one of my work's major projects we move up the SDK to the latest to get language features, but still need to target .NET Framework 4.8 because of 3rd party libraries that are not available for .NET Core.
> 
> So we could put `[OverloadResolutionPriorityAttribute]` in and people only have to update the SDK to take advantage of it. I'll try this, but the success rate for the last issue (picking `object` overload over `string`) didn't work. It always picked one or the other.

@manfred-brands Yes, my company also targets .NET Framework 4.8 with the latest SDK (and language version too).

Things to clarify:

- OverloadResolutionPriorityAttribute works only with LangVersion 13+. 
- SDK version isn't directly what matters, only LangVersion being 13+. This constrains you of course to SDKs that are capable of using LangVersion 13+.
- OverloadResolutionPriorityAttribute works regardless of target framework, so long as LangVersion is 13+. To use OverloadResolutionPriorityAttribute on downlevel target frameworks, declare it in source once per project as internal inside `#if !NET9_0_OR_GREATER`.

But OverloadResolutionPriorityAttribute does no good if you don't target LangVersion 13+. And many people target .NET Framework 4.8 or .NET 8.0 without overriding LangVersion, so they use an older langversion by default. And for those people, OverloadResolutionPriorityAttribute makes no difference at all.

This is why Shouldly only added the new overloads when targeting .NET 9. That way it's less confusing for users. People on .NET 8.0 and .NET Framework 4.8 don't get the new overloads at all. Alternatively, you could make the tradeoff of adding the new overloads on all targets, and responding to an influx of "I'm getting a new overload resolution ambiguity" with "then upgrade your LangVersion to 13+." To which they might (reasonably) respond "Microsoft says that's not a supported scenario, so I don't want to."

**Comment by appel1** [comment]
@manfred-brands Yes, that works. In cases where you new up the comparer or can't change the method signature you have to create a factory method or cast.

**Comment by OsirisTerje** [comment]
@manfred-brands   The work around you suggested seems to fix this for now.
Any reason to keep this open ?

**Comment by manfred-brands** [comment]
@OsirisTerje I was thinking of removing support for the non-generic comparers on the new generic overloads.

The problem is that this might break old code where users handcoded a comparer and not implemented the generic version.

Let me try how much it breaks on our own tests.
We can then either mark the overloads as obsolete or see if the new overload resolution solves it.

**Comment by manfred-brands** [comment]
My branch with the `OverloadResolutionAttribute` suddenly works.

The only difference is that it now compiles with 9.0.200 SDK.
To verify that it wasn't me, I changed global.json to restrict it to 9.0.1xx and I get compile errors.

```txt
EqualConstraintTests.cs(989,56): error CS1503: Argument 2: cannot convert from 'System.Collections.IEqualityComparer' to 'System.Collections.Generic.IEqualityComparer<int>'
```

@jnm2 I can't find any release notes or issues closed mentioning `OverloadResolutionPriority` fixes in 9.0.200 (or msbuild 17.13)
Do you have any inside knowledge?

**Comment by jnm2** [comment]
Indeed, `dotnet build` in SDK 9.0.103 fails, and 9.0.200 succeeds. I don't have inside knowledge. Interesting how the net462 build of the same project succeeds when the net9.0 build fails.

**Comment by jnm2** [comment]
I filed https://github.com/dotnet/roslyn/issues/77422 to track this. It appears to be a bug in SDK 9.0.103 which affects anyone that uses that SDK and targets .NET 9 while using a library that targets .NET 8 which uses ORPA (OverloadResolutionPriorityAttribute) in its APIs.

**Comment by jnm2** [comment]
@manfred-brands As a workaround, NUnit could add a `net9.0` target and then wrap `#if !NET9_0_OR_GREATER` around the declaration of the internal OverloadResolutionPriorityAttribute. The issue is only present when the consuming project is targeting net9.0 or later and the assembly it is referencing is targeting net8.0 or earlier.

**Comment by manfred-brands** [comment]
@jnm2 That is indeed weird. It is as if `OverloadResolutionPriorityAttribute` isn't considered by the 9.0.1xx SDK when the target doesn't match the consuming as it does take it into account for  the net462/net462, net6.0/net6.0 and net8.0/net8.0 build combinations.

As it is solved in the 9.0.2xx SDK, I don't want to introduce a new target just for this.
I did add an #if !NET9_0_OR_GREATER protection around the `OverloadResolutionPriorityAttribute` to future proof it.

P.S. I see you got as much reactions on your roslyn ticket as I normally get.

**Comment by jnm2** [comment]
I think it's even weirder than just not being considered. If the attribute had no effect, then there would be no error: only one of the two overloads accepts non-generic IEqualityComparer, which is what is being passed. But instead, the attribute chooses the _wrong_ overload and causes the error that `IEqualityComparer` is not `IEqualityComparer<T>`.
