### ISSUE TITLE
NUnit 3.10.1 'TestContext.PropertyBagAdapter' does not contain a definition for 'Set'

### ISSUE THREAD

**Issue by kirbycope** [nunit/nunit#2760]
After upgrading from 3.9 to 3.10.1, I receive the following build error:

> error CS1061: 'TestContext.PropertyBagAdapter' does not contain a definition for 'Set' and no extension method 'Set' accepting a first argument of type 'TestContext.PropertyBagAdapter' could be found (are you missing a using directive or an assembly reference?)

The code in question:

>         public static void Set(string key, object value)
>         {
>             NUnit.Framework.TestContext.CurrentContext.Test.Properties.Set(key, value);
>         }

If I revert the NuGet package to 3.9 all is well.

**Comment by mikkelbu** [comment]
Hi @kirbycope. I think you can use `TestExecutionContext.CurrentContext.CurrentTest.Properties` instead (the solution was mentioned in #1578).

**Comment by kirbycope** [comment]
@mikkelbu That did the trick, thanks!

**Comment by CharliePoole** [comment]
However, it's not intended that you should change the properties of an NUnit Test, because Test and its derivatives are internal and the implementation can change. The internal classes allow it because custom attributes may need to do it, but I recommend that tests avoid doing it.

We might consider creating a special set of user properties available for tests to communicate with if there is really a need.

**Comment by elv1s42** [comment]
Hi @CharliePoole , having user properties (with Get/Set/Add methods) would be very useful. 
At the moment I have the similar issue with Set method which is not available anymore.

Thank you

**Comment by pshort** [comment]
@CharliePoole Im using these properties to create a "Test Context". Tests use this context and helpers etc can refer to the context down the stack if needed (like get the current randomly generated username and password etc)

**Comment by jnm2** [comment]
@pshort Out of curiosity, what would it take for you to switch to using a static class to store this context rather than using NUnit test properties?

**Comment by CreatedJustForComments** [comment]
@jnm2 I do the exact same thing, because I only want the properties to exist in the scope of the Test and be accesible by any method called by that test

**Comment by jnm2** [comment]
@CreatedJustForComments I would very much recommend passing such properties as parameters (fancy term is dependency injection) rather than locating them through a static class such as `TestContext`. This is a coding style that documents the true dependencies of the helper methods.

**Comment by jnm2** [comment]
@CreatedJustForComments I would very much recommend passing such properties as parameters (fancy term is dependency injection) rather than locating them through a static class such as `TestContext`. This is a coding style that documents the true dependencies of the helper methods.

Instead of:

```cs
[Test]
public void Test()
{
    TestContext.CurrentContext.Test.Properties.Set("x", 42);
    HelperMethod();
}

private void HelperMethod()
{
    var x = (int)TestContext.CurrentContext.Test.Properties.Get("x", 42);
    // Do something with x
}
```

Using pure functions is cleaner:


```cs
[Test]
public void Test()
{
    HelperMethod(x: 42);
}

private void HelperMethod(int x)
{
    // Do something with x
}
```

**Comment by CreatedJustForComments** [comment]
I'm using a Page Object Design Pattern. That means that helperMethod1("key") stores a value and get("key") gets the value. I don't want to introduce variables in my test method as it is against the design pattern. 
Snap of my vb.net:
`
    Public Sub StoreValue(key As String, value As String)
        TestExecutionContext.CurrentContext.CurrentTest.Properties.Add(key, value)
    End Sub`

`Public Sub StorePageTitle(key As String)
        StoreValue(key, "pageTitle")
End Sub`

`
<Test()>
Public Sub Test123()
      StorePageTitle("title")
      Assert.AreEqual(Get("title"), "pageTitle")
End Sub`

Sorry if i went off topic, but this is my exact need, and the reason i use textContext

**Comment by CharliePoole** [comment]
@CreatedJustForComments It's not a bad pattern that you're using. It's just not something that TestContext was intended to do. TestContext was built as a way for the test code to access basic info about the test, including the properties of the test.

Problem is, once a test is executing, the properties of the test are already set in stone. They need to be because they are the properties of the __test__ not of the particular __test execution__. NUnit uses many of these properties internally, so we only want to let you peek at them, not change them. And, of course, allowing you to set properties also allows you to change NUnit's own properties if you happen to know the key.

@jnm2 I thought we had an issue to add "user properties" or "result properties" to the context but I can't seem to find it. I think we really do need something to deal with this issue. User should have a place to to store stuff and get it back as needed, without the risk of interfering with NUnit's internal operation.

**Comment by jnm2** [comment]
@CreatedJustForComments Not off topic at all, precisely the kind of information I was probing for. What people usually do in this scenario is maintain a static dictionary to map `TestContext.CurrentContext.Test.ID` to a property or a properties object.

It looks like you are simply verifying the behavior of `StorePageTitle`. How would you have implemented `StoreValue` for your product assembly which does not reference NUnit?

@CharliePoole Seems like it would be nice. I'm not sure it's a good thing to encourage code to use that pattern though, and the workaround is simple.

@CharliePoole It looks like all C is doing is verifying the behavior of `StorePageTitle`

**Comment by CharliePoole** [comment]
@jnm2 I agree that for this usage, it seems like an overly complex solution. But I recall we had other cases where, for example, a SetUpFixture needed to leave info for the tests and we discussed implementing a set of properties that could be used for the purpose. A blackboard might be an option as well. Wish I could find the discussion!

**Comment by stokescomp** [comment]
The reason I need to be able to change the properties is because I made a custom attribute but if it is a parameterized test using TestCaseSource it doesn't apply my custom TestCaseKey attribute to all the parameterized tests. It does add it properly if it is a normal test though.

```
[Test, TestCaseKey(635), TestCaseSource("GetUsers")]
public void VerifyUserTest(User user)
        {
            TestExecutionContext.CurrentContext.CurrentTest.Properties.Add("TestCaseKey", 635);
//do stuff for each user
}
```

So I put that one line in each parameterized test so the test case key is added. Then later I get the testcasekey to record the results in the database for each parameterized test.
I get the value of the testcasekey using: 
TestContext.CurrentContext.Test.Properties["TestCaseKey"].ToString()

**Comment by CharliePoole** [comment]
Ah! That's a real problem. It's not a use case I had ever considered.

**Comment by jnm2** [comment]
@stokescomp Would something like this make sense?

```cs
public static IEnumerable<TestCaseData> GetUsers(int testCaseKey)
{
    return new[]
    {
        new TestCaseData(new User { ... }).SetProperty("TestCaseKey", testCaseKey)
    };
}

[Test, TestCaseSource(nameof(GetUsers), 635)]
public void VerifyUserTest(User user)
{
    // do stuff for each user
}
```

**Comment by CharliePoole** [comment]
@jnm2 Good on you! I should have pointed that out.

I do think that some attributes should be re-defined to apply to the cases rather than the method suite. Maybe even all of them. After all, the method suite is purely an artificial construct we create ourselves in order to group the test cases.
